import type { RegistryEntry } from "../../../shared.ts";

export const github_modelsProvider: RegistryEntry = {
  id: "github-models",
  alias: "ghm",
  format: "openai",
  executor: "default",
  baseUrl: "https://models.github.ai/inference/chat/completions",
  modelsUrl: "https://models.github.ai/catalog/models",
  authType: "apikey",
  authHeader: "Authorization",
  authPrefix: "Bearer",
  headers: {
    "X-GitHub-Api-Version": "2026-03-10",
    Accept: "application/vnd.github+json",
  },
  defaultContextLength: 128000,
  models: [
    {
      id: "cohere/cohere-command-a",
      name: "Cohere Command A",
      contextLength: 131_072,
      maxInputTokens: 131_072,
      maxOutputTokens: 4_096,
    },
    {
      id: "deepseek/deepseek-r1-0528",
      name: "DeepSeek-R1-0528",
      contextLength: 128_000,
      maxInputTokens: 128_000,
      maxOutputTokens: 4_096,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "deepseek/deepseek-v3-0324",
      name: "DeepSeek-V3-0324",
      contextLength: 128_000,
      maxInputTokens: 128_000,
      maxOutputTokens: 4_096,
      toolCalling: true,
    },
    {
      id: "meta/llama-4-maverick-17b-128e-instruct-fp8",
      name: "Llama 4 Maverick 17B 128E Instruct FP8",
      contextLength: 1_000_000,
      maxInputTokens: 1_000_000,
      maxOutputTokens: 4_096,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "meta/llama-3.3-70b-instruct",
      name: "Llama-3.3-70B-Instruct",
      contextLength: 128_000,
      maxInputTokens: 128_000,
      maxOutputTokens: 4_096,
    },
    {
      id: "meta/llama-4-scout-17b-16e-instruct",
      name: "Llama 4 Scout 17B 16E Instruct",
      contextLength: 10_000_000,
      maxInputTokens: 10_000_000,
      maxOutputTokens: 4_096,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "microsoft/phi-4-multimodal-instruct",
      name: "Phi-4-multimodal-instruct",
      contextLength: 128_000,
      maxInputTokens: 128_000,
      maxOutputTokens: 4_096,
      supportsVision: true,
    },
    {
      id: "microsoft/phi-4-reasoning",
      name: "Phi-4-reasoning",
      contextLength: 32_768,
      maxInputTokens: 32_768,
      maxOutputTokens: 4_096,
      supportsReasoning: true,
    },
    {
      id: "mistral-ai/codestral-2501",
      name: "Codestral 25.01",
      contextLength: 256_000,
      maxInputTokens: 256_000,
      maxOutputTokens: 4_096,
    },
    {
      id: "mistral-ai/mistral-medium-2505",
      name: "Mistral Medium 3 (25.05)",
      contextLength: 128_000,
      maxInputTokens: 128_000,
      maxOutputTokens: 4_096,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-4.1",
      name: "OpenAI GPT-4.1",
      contextLength: 1_048_576,
      maxInputTokens: 1_048_576,
      maxOutputTokens: 32_768,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-4.1-mini",
      name: "OpenAI GPT-4.1-mini",
      contextLength: 1_048_576,
      maxInputTokens: 1_048_576,
      maxOutputTokens: 32_768,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-4o",
      name: "OpenAI GPT-4o",
      contextLength: 131_072,
      maxInputTokens: 131_072,
      maxOutputTokens: 16_384,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-4o-mini",
      name: "OpenAI GPT-4o mini",
      contextLength: 131_072,
      maxInputTokens: 131_072,
      maxOutputTokens: 4_096,
      supportsVision: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-5",
      name: "OpenAI gpt-5",
      contextLength: 200_000,
      maxInputTokens: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-5-chat",
      name: "OpenAI gpt-5-chat (preview)",
      contextLength: 200_000,
      maxInputTokens: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "openai/gpt-5-mini",
      name: "OpenAI gpt-5-mini",
      contextLength: 200_000,
      maxInputTokens: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "openai/o3",
      name: "OpenAI o3",
      contextLength: 200_000,
      maxInputTokens: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
    {
      id: "openai/o4-mini",
      name: "OpenAI o4-mini",
      contextLength: 200_000,
      maxInputTokens: 200_000,
      maxOutputTokens: 100_000,
      supportsVision: true,
      supportsReasoning: true,
      toolCalling: true,
    },
  ],
};
