package quota

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// diffeq_test.go — Differential-equivalence replay.
//
// The fixtures in testdata/diffeq_fixtures.json were generated by running the
// REAL TypeScript implementations (diffeq_gen.ts via tsx). This test replays
// the exact same inputs through the Go port and asserts identical outputs.
// This is the ground-truth equivalence check (not self-referential Go
// expectations).

type diffFixtures struct {
	FairShare    []fairShareFixture    `json:"fairShare"`
	BurnRate     []burnRateFixture     `json:"burnRate"`
	Naming       []namingFixture       `json:"naming"`
	PlanRegistry []planRegistryFixture `json:"planRegistry"`
	Buckets      []bucketFixture       `json:"buckets"`
}

type planRegistryFixture struct {
	Fn       string          `json:"fn"`
	Input    json.RawMessage `json:"input"`
	Expected json.RawMessage `json:"expected"`
}

type bucketFixture struct {
	Ops []struct {
		Fn   string            `json:"fn"`
		Args []json.RawMessage `json:"args"`
	} `json:"ops"`
	Expected struct {
		Saturated map[string]bool `json:"saturated"`
		Count     int             `json:"count"`
	} `json:"expected"`
}

type fairShareFixture struct {
	Input    json.RawMessage `json:"input"`
	Expected json.RawMessage `json:"expected"`
}

type burnRateFixture struct {
	Input struct {
		History   []struct {
			TS       float64 `json:"ts"`
			Consumed float64 `json:"consumed"`
		} `json:"history"`
		Remaining *float64 `json:"remaining"`
	} `json:"input"`
	Expected struct {
		TokensPerSecond    float64  `json:"tokensPerSecond"`
		TimeToExhaustionMs *float64 `json:"timeToExhaustionMs"`
	} `json:"expected"`
}

type namingFixture struct {
	Fn       string          `json:"fn"`
	Input    json.RawMessage `json:"input"`
	Expected json.RawMessage `json:"expected"`
}

func loadFixtures(t *testing.T) diffFixtures {
	t.Helper()
	data, err := os.ReadFile("testdata/diffeq_fixtures.json")
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	var f diffFixtures
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}
	return f
}

// ---------------------------------------------------------------------------
// fairShare replay
// ---------------------------------------------------------------------------

type tsFairShareInput struct {
	Dimensions []struct {
		Key struct {
			PoolID string `json:"poolId"`
			Unit   string `json:"unit"`
			Window string `json:"window"`
		} `json:"key"`
		Limit             float64 `json:"limit"`
		ConsumedTotal     float64 `json:"consumedTotal"`
		GlobalUsedPercent float64 `json:"globalUsedPercent"`
	} `json:"dimensions"`
	Allocation struct {
		Weight   float64  `json:"weight"`
		CapValue *float64 `json:"capValue"`
		CapUnit  *string  `json:"capUnit"`
		Policy   string   `json:"policy"`
	} `json:"allocation"`
	ConsumedByThisKey   map[string]float64 `json:"consumedByThisKey"`
	SaturationThreshold float64            `json:"saturationThreshold"`
}

type tsFairShareExpected struct {
	Kind      string `json:"kind"`
	Reason    string `json:"reason"`
	Penalized *bool  `json:"penalized"`
}

func TestDiffEqFairShare(t *testing.T) {
	fx := loadFixtures(t)
	if len(fx.FairShare) == 0 {
		t.Fatal("no fairShare fixtures")
	}
	for i, f := range fx.FairShare {
		var in tsFairShareInput
		if err := json.Unmarshal(f.Input, &in); err != nil {
			t.Fatalf("case %d: parse input: %v", i, err)
		}
		var exp tsFairShareExpected
		if err := json.Unmarshal(f.Expected, &exp); err != nil {
			t.Fatalf("case %d: parse expected: %v", i, err)
		}

		// Build Go input.
		dims := make([]FairShareDimension, len(in.Dimensions))
		for j, d := range in.Dimensions {
			dims[j] = FairShareDimension{
				Key: DimensionKey{
					PoolID: d.Key.PoolID,
					Unit:   QuotaUnit(d.Key.Unit),
					Window: QuotaWindow(d.Key.Window),
				},
				Limit:             d.Limit,
				ConsumedTotal:     d.ConsumedTotal,
				GlobalUsedPercent: d.GlobalUsedPercent,
			}
		}
		alloc := FairShareAllocation{
			Weight: in.Allocation.Weight,
			Policy: Policy(in.Allocation.Policy),
		}
		if in.Allocation.CapValue != nil {
			alloc.CapValue = in.Allocation.CapValue
			if in.Allocation.CapUnit != nil {
				alloc.CapUnit = QuotaUnit(*in.Allocation.CapUnit)
			}
		}
		consumed := in.ConsumedByThisKey
		if consumed == nil {
			consumed = map[string]float64{}
		}

		got := DecideFairShare(FairShareInput{
			Dimensions:          dims,
			Allocation:          alloc,
			ConsumedByThisKey:   consumed,
			SaturationThreshold: in.SaturationThreshold,
		})

		// Compare kind + reason.
		if string(got.Kind) != exp.Kind {
			t.Errorf("case %d: kind = %q, TS expected %q (input=%s)", i, got.Kind, exp.Kind, string(f.Input))
		}
		if string(got.Reason) != exp.Reason {
			t.Errorf("case %d: reason = %q, TS expected %q (input=%s)", i, got.Reason, exp.Reason, string(f.Input))
		}
		// Compare penalized: TS omits when false; treat nil as false.
		expPen := exp.Penalized != nil && *exp.Penalized
		if got.Penalized != expPen {
			t.Errorf("case %d: penalized = %v, TS expected %v (input=%s)", i, got.Penalized, expPen, string(f.Input))
		}
	}
	t.Logf("fairShare: %d cases matched TS ground truth", len(fx.FairShare))
}

// ---------------------------------------------------------------------------
// burnRate replay
// ---------------------------------------------------------------------------

func TestDiffEqBurnRate(t *testing.T) {
	fx := loadFixtures(t)
	if len(fx.BurnRate) == 0 {
		t.Fatal("no burnRate fixtures")
	}
	for i, f := range fx.BurnRate {
		history := make([]BurnRateSample, len(f.Input.History))
		for j, s := range f.Input.History {
			history[j] = BurnRateSample{TS: s.TS, Consumed: s.Consumed}
		}
		got := ComputeBurnRate(history, f.Input.Remaining)

		// tokensPerSecond must match within float tolerance.
		if math.Abs(got.TokensPerSecond-f.Expected.TokensPerSecond) > 1e-9 {
			t.Errorf("case %d: tokensPerSecond = %v, TS expected %v", i, got.TokensPerSecond, f.Expected.TokensPerSecond)
		}
		// timeToExhaustionMs: TS null ↔ Go NaN.
		if f.Expected.TimeToExhaustionMs == nil {
			if !math.IsNaN(got.TimeToExhaustionMs) {
				t.Errorf("case %d: timeToExhaustionMs = %v, TS expected null", i, got.TimeToExhaustionMs)
			}
		} else {
			if math.IsNaN(got.TimeToExhaustionMs) || math.Abs(got.TimeToExhaustionMs-*f.Expected.TimeToExhaustionMs) > 1e-6 {
				t.Errorf("case %d: timeToExhaustionMs = %v, TS expected %v", i, got.TimeToExhaustionMs, *f.Expected.TimeToExhaustionMs)
			}
		}
	}
	t.Logf("burnRate: %d cases matched TS ground truth", len(fx.BurnRate))
}

// ---------------------------------------------------------------------------
// naming replay
// ---------------------------------------------------------------------------

func TestDiffEqNaming(t *testing.T) {
	fx := loadFixtures(t)
	if len(fx.Naming) == 0 {
		t.Fatal("no naming fixtures")
	}
	for i, f := range fx.Naming {
		switch f.Fn {
		case "quotaGroupSlug", "quotaPoolSlug":
			var in string
			json.Unmarshal(f.Input, &in)
			var exp string
			json.Unmarshal(f.Expected, &exp)
			var got string
			if f.Fn == "quotaGroupSlug" {
				got = QuotaGroupSlug(in)
			} else {
				got = QuotaPoolSlug(in)
			}
			if got != exp {
				t.Errorf("case %d %s(%q) = %q, TS expected %q", i, f.Fn, in, got, exp)
			}
		case "isQuotaModelName":
			var in string
			json.Unmarshal(f.Input, &in)
			var exp bool
			json.Unmarshal(f.Expected, &exp)
			if got := IsQuotaModelName(in); got != exp {
				t.Errorf("case %d isQuotaModelName(%q) = %v, TS expected %v", i, in, got, exp)
			}
		case "quotaModelName":
			var in []string
			json.Unmarshal(f.Input, &in)
			var exp string
			json.Unmarshal(f.Expected, &exp)
			if got := QuotaModelName(in[0], in[1], in[2]); got != exp {
				t.Errorf("case %d quotaModelName(%v) = %q, TS expected %q", i, in, got, exp)
			}
		case "parseQuotaModelName":
			var in string
			json.Unmarshal(f.Input, &in)
			expRaw := string(f.Expected)
			got := ParseQuotaModelName(in)
			if expRaw == "null" {
				if got != nil {
					t.Errorf("case %d parseQuotaModelName(%q) = %+v, TS expected null", i, in, got)
				}
			} else {
				if got == nil {
					t.Errorf("case %d parseQuotaModelName(%q) = nil, TS expected %s", i, in, expRaw)
				} else {
					var exp struct {
						GroupSlug string `json:"groupSlug"`
						Provider  string `json:"provider"`
						Model     string `json:"model"`
					}
					json.Unmarshal(f.Expected, &exp)
					if got.GroupSlug != exp.GroupSlug || got.Provider != exp.Provider || got.Model != exp.Model {
						t.Errorf("case %d parseQuotaModelName(%q) = %+v, TS expected %+v", i, in, got, exp)
					}
				}
			}
		default:
			t.Errorf("case %d: unknown fn %q", i, f.Fn)
		}
	}
	t.Logf("naming: %d cases matched TS ground truth", len(fx.Naming))
}

// ---------------------------------------------------------------------------
// planRegistry replay
// ---------------------------------------------------------------------------

func TestDiffEqPlanRegistry(t *testing.T) {
	fx := loadFixtures(t)
	if len(fx.PlanRegistry) == 0 {
		t.Fatal("no planRegistry fixtures")
	}
	for i, f := range fx.PlanRegistry {
		switch f.Fn {
		case "getKnownPlan":
			var provider string
			json.Unmarshal(f.Input, &provider)
			got := GetKnownPlan(provider)
			expRaw := string(f.Expected)
			if expRaw == "null" {
				if got != nil {
					t.Errorf("case %d getKnownPlan(%q) = %+v, TS expected null", i, provider, got)
				}
				continue
			}
			if got == nil {
				t.Errorf("case %d getKnownPlan(%q) = nil, TS expected %s", i, provider, expRaw)
				continue
			}
			var exp struct {
				Provider   string `json:"provider"`
				Dimensions []struct {
					Unit   string  `json:"unit"`
					Window string  `json:"window"`
					Limit  float64 `json:"limit"`
				} `json:"dimensions"`
			}
			json.Unmarshal(f.Expected, &exp)
			if got.Provider != exp.Provider {
				t.Errorf("case %d provider = %q, TS expected %q", i, got.Provider, exp.Provider)
			}
			if len(got.Dimensions) != len(exp.Dimensions) {
				t.Errorf("case %d dims len = %d, TS expected %d", i, len(got.Dimensions), len(exp.Dimensions))
				continue
			}
			for j, d := range got.Dimensions {
				ed := exp.Dimensions[j]
				if string(d.Unit) != ed.Unit || string(d.Window) != ed.Window {
					t.Errorf("case %d dim[%d] = %s/%s, TS expected %s/%s", i, j, d.Unit, d.Window, ed.Unit, ed.Window)
				}
				// Limit: exact float match (LimitUnknown == Number.EPSILON).
				if d.Limit != ed.Limit {
					t.Errorf("case %d dim[%d] limit = %v, TS expected %v", i, j, d.Limit, ed.Limit)
				}
			}
		case "knownProviders":
			got := KnownProviders()
			var exp []string
			json.Unmarshal(f.Expected, &exp)
			if len(got) != len(exp) {
				t.Errorf("case %d knownProviders len = %d, TS expected %d", i, len(got), len(exp))
				continue
			}
			for j := range got {
				if got[j] != exp[j] {
					t.Errorf("case %d knownProviders[%d] = %q, TS expected %q", i, j, got[j], exp[j])
				}
			}
		default:
			t.Errorf("case %d: unknown fn %q", i, f.Fn)
		}
	}
	t.Logf("planRegistry: %d cases matched TS ground truth", len(fx.PlanRegistry))
}

// ---------------------------------------------------------------------------
// buckets replay (stateful op sequences)
// ---------------------------------------------------------------------------

func TestDiffEqBuckets(t *testing.T) {
	fx := loadFixtures(t)
	if len(fx.Buckets) == 0 {
		t.Fatal("no buckets fixtures")
	}
	for i, f := range fx.Buckets {
		store := NewBucketStore()
		gotSaturated := map[string]bool{}
		for _, op := range f.Ops {
			switch op.Fn {
			case "recordUsage":
				var connID, windowKey string
				var usedPct float64
				var resetAt *string
				var nowMs int64
				json.Unmarshal(op.Args[0], &connID)
				json.Unmarshal(op.Args[1], &windowKey)
				json.Unmarshal(op.Args[2], &usedPct)
				json.Unmarshal(op.Args[3], &resetAt)
				json.Unmarshal(op.Args[4], &nowMs)
				ra := ""
				if resetAt != nil {
					ra = *resetAt
				}
				store.RecordUsage(connID, windowKey, usedPct, ra, nowMs)
			case "isBucketSaturated":
				var connID, windowKey string
				var nowMs int64
				json.Unmarshal(op.Args[0], &connID)
				json.Unmarshal(op.Args[1], &windowKey)
				json.Unmarshal(op.Args[2], &nowMs)
				gotSaturated[connID+"::"+windowKey] = store.IsBucketSaturated(connID, windowKey, nowMs)
			case "updateAccountBuckets":
				var connID string
				var nowMs int64
				json.Unmarshal(op.Args[0], &connID)
				json.Unmarshal(op.Args[2], &nowMs)
				// Parse quotas map: args[1] is {quotas: {key: {used, total, resetAt}}}
				var usageRaw struct {
					Quotas map[string]struct {
						Used    float64 `json:"used"`
						Total   float64 `json:"total"`
						ResetAt *string `json:"resetAt"`
					} `json:"quotas"`
				}
				json.Unmarshal(op.Args[1], &usageRaw)
				var usage *ClaudeUsageResult
				if usageRaw.Quotas != nil {
					quotas := make(map[string]UsageQuotaSlim)
					for k, v := range usageRaw.Quotas {
						ra := ""
						if v.ResetAt != nil {
							ra = *v.ResetAt
						}
						quotas[k] = UsageQuotaSlim{Used: v.Used, ResetAt: ra}
					}
					usage = &ClaudeUsageResult{Quotas: quotas}
				}
				store.UpdateAccountBuckets(connID, usage, nowMs)
			}
		}
		// Compare saturated map.
		for key, expVal := range f.Expected.Saturated {
			if gotSaturated[key] != expVal {
				t.Errorf("case %d saturated[%q] = %v, TS expected %v", i, key, gotSaturated[key], expVal)
			}
		}
		// Compare bucket count.
		if got := store.BucketCount(); got != f.Expected.Count {
			t.Errorf("case %d bucketCount = %d, TS expected %d", i, got, f.Expected.Count)
		}
	}
	t.Logf("buckets: %d cases matched TS ground truth", len(fx.Buckets))
}
